/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResponsibleAiRouteImport } from './routes/responsible-ai'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppEmailRouteImport } from './routes/app.email'
import { Route as AppHistoryRouteImport } from './routes/app.history'
import { Route as AppMeetingsRouteImport } from './routes/app.meetings'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppTasksRouteImport } from './routes/app.tasks'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResponsibleAiRoute = ResponsibleAiRouteImport.update({
  id: '/responsible-ai',
  path: '/responsible-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppEmailRoute = AppEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppMeetingsRoute = AppMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/responsible-ai': typeof ResponsibleAiRoute
  '/app/email': typeof AppEmailRoute
  '/app/history': typeof AppHistoryRoute
  '/app/meetings': typeof AppMeetingsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/responsible-ai': typeof ResponsibleAiRoute
  '/app/email': typeof AppEmailRoute
  '/app/history': typeof AppHistoryRoute
  '/app/meetings': typeof AppMeetingsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tasks': typeof AppTasksRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/responsible-ai': typeof ResponsibleAiRoute
  '/app/email': typeof AppEmailRoute
  '/app/history': typeof AppHistoryRoute
  '/app/meetings': typeof AppMeetingsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/responsible-ai'
    | '/app/email'
    | '/app/history'
    | '/app/meetings'
    | '/app/settings'
    | '/app/tasks'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/responsible-ai'
    | '/app/email'
    | '/app/history'
    | '/app/meetings'
    | '/app/settings'
    | '/app/tasks'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/responsible-ai'
    | '/app/email'
    | '/app/history'
    | '/app/meetings'
    | '/app/settings'
    | '/app/tasks'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResponsibleAiRoute: typeof ResponsibleAiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/responsible-ai': {
      id: '/responsible-ai'
      path: '/responsible-ai'
      fullPath: '/responsible-ai'
      preLoaderRoute: typeof ResponsibleAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/email': {
      id: '/app/email'
      path: '/email'
      fullPath: '/app/email'
      preLoaderRoute: typeof AppEmailRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/history': {
      id: '/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/meetings': {
      id: '/app/meetings'
      path: '/meetings'
      fullPath: '/app/meetings'
      preLoaderRoute: typeof AppMeetingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tasks': {
      id: '/app/tasks'
      path: '/tasks'
      fullPath: '/app/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppEmailRoute: typeof AppEmailRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppMeetingsRoute: typeof AppMeetingsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTasksRoute: typeof AppTasksRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppEmailRoute: AppEmailRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppMeetingsRoute: AppMeetingsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTasksRoute: AppTasksRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ResponsibleAiRoute: ResponsibleAiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
